exports.colors = [
    'amaranth',
    'amber',
    'amethyst',
    'apricot',
    'aquamarine',
    'azure',
    'baby blue',
    'beige',
    'black',
    'blue',
    'blue-green',
    'blue-violet',
    'blush',
    'bronze',
    'brown',
    'burgundy',
    'byzantium',
    'carmine',
    'cerise',
    'cerulean',
    'champagne',
    'chartreuse green',
    'chocolate',
    'cobalt blue',
    'coffee',
    'copper',
    'coral',
    'crimson',
    'cyan',
    'desert sand',
    'electric blue',
    'emerald',
    'erin',
    'gold',
    'gray',
    'green',
    'harlequin',
    'indigo',
    'ivory',
    'jade',
    'jungle green',
    'lavender',
    'lemon',
    'lilac',
    'lime',
    'magenta',
    'magenta rose',
    'maroon',
    'mauve',
    'navy blue',
    'ocher',
    'olive',
    'orange',
    'orange-red',
    'orchid',
    'peach',
    'pear',
    'periwinkle',
    'persian blue',
    'pink',
    'plum',
    'prussian blue',
    'puce',
    'purple',
    'raspberry',
    'red',
    'red-violet',
    'rose',
    'ruby',
    'salmon',
    'sangria',
    'sapphire',
    'scarlet',
    'silver',
    'slate gray',
    'spring bud',
    'spring green',
    'tan',
    'taupe',
    'teal',
    'turquoise',
    'violet',
    'viridian',
    'white',
    'yankees blue',
    'yellow',
];

exports.adjectives = [
    'heavy',
    'fat',
    'slow',
    'short',
    'nerdy',
    'silly',
    'soft',
    'warm',
    'sexy',
    'plump',
    'pulsating',
    'squishy',
    'toasty',
    'hard',
    'angry',    
    'happy',
    'sad',
    'melting',
    'giant',
    'gentlemanlike',
    'burnt',
    'insane',
    'dead',
    'wiggly',
    'exploding',
    'crazy',
    'short',
    'glowing',
    'bouncing',
    'prancing',
    'floating',
    'flying',
    'swimming',
    'diving',
    'yummy',
    'gyrating',
    'prickly',
    'sleepy',
    'foolish',
    'evil',
];

exports.nouns = [
    'turtle',
    'penguin',
    'lobster',
    'elephant',
    'squid',
    'diamond',
    'tiger',
    'lion',
    'giraffe',
    'grasshopper',
    'dragon',
    'unicorn',
    'dolphin',
    'gnome',
    'toast',
    'elf',
    'deer',
    'book',
    'jello',
    'shark',
    'booger',
    'zombie',
    'vampire',
    'werewolf',
    'bunny',
    'rabbit',
    'box',
    'guitar',
    'computer',
    'car',
    'weather',
    'impala',
    'panda',
    'toilet',
    'mango',
    'kiwi',
    'apple',
    'durian',
    'tree',
    'racoon',
    'hero',
    'villian',
];