module.exports = [
  'map/connected-top-bottom', 'map/connected-top-bottom', 'map/connected-top-bottom', 'map/connected-top-bottom', 'map/connected-top-bottom', 
  'map/connected-right-left', 'map/connected-right-left', 'map/connected-right-left', 'map/connected-right-left', 'map/connected-right-left', 
  'map/connected-top-right', 'map/connected-top-right', 'map/connected-top-right', 'map/connected-top-right', 'map/connected-top-right', 
  'map/connected-top-left', 'map/connected-top-left', 'map/connected-top-left', 'map/connected-top-left', 'map/connected-top-left', 
  'map/connected-top-right-bottom', 'map/connected-top-right-bottom', 'map/connected-top-right-bottom', 'map/connected-top-right-bottom', 'map/connected-top-right-bottom', 
  'map/connected-top-right-left', 'map/connected-top-right-left', 'map/connected-top-right-left', 'map/connected-top-right-left', 'map/connected-top-right-left', 
  'map/connected-cross', 'map/connected-cross', 'map/connected-cross', 'map/connected-cross', 'map/connected-cross', 
  
  'map/deadend-top',
  'map/deadend-right',
  'map/deadend-top-right',
  'map/deadend-top-left',
  'map/deadend-top-bottom',
  'map/deadend-right-left',
  'map/deadend-top-right-bottom',
  'map/deadend-top-right-left',
  'map/deadend-cross',
  
  'action/free-pickaxe', 'action/free-pickaxe', 
  'action/free-lamp', 'action/free-lamp', 
  'action/free-cart', 'action/free-cart', 
  'action/free-pickaxe-lamp',
  'action/free-pickaxe-cart',
  'action/free-lamp-cart',
  'action/block-pickaxe', 'action/block-pickaxe', 'action/block-pickaxe', 
  'action/block-lamp', 'action/block-lamp', 'action/block-lamp', 
  'action/block-cart', 'action/block-cart', 'action/block-cart', 
  
  'action/avalanche', 'action/avalanche', 'action/avalanche', 
  'action/map', 'action/map', 'action/map', 'action/map', 'action/map', 'action/map', 'action/map', 
];
