module.exports = [
  'connected top bottom',
  'connected right left',
  'connected top right',
  'connected top left',
  'connected top right bottom',
  'connected top right left',
  'connected cross',
  'deadend top',
  'deadend right',
  'deadend top right',
  'deadend top left',
  'deadend top bottom',
  'deadend right left',
  'deadend top right bottom',
  'deadend top right left',
  'deadend cross',
  'free pickaxe',
  'free light',
  'free cart',
  'block pickaxe',
  'block light',
  'block cart',
  'avalanche',
  'map'
];
